/**********************************************************************************************************************
 *  FILE DESCRIPTION
 *  -----------------------------------------------------------------------------------------------------------------
 *
 *         @Date:  	11:23 PM Monday, May 15, 2023
 *		   @File:  	delay_program.c         
 *		 @Module:  	Delay generated by timer on normal mode
 *		 @Author:	Ahmed Hesham
 *  @Description:  	Program file for Delay generated by timer on normal mode
 *  
 *********************************************************************************************************************/

/**********************************************************************************************************************
 *  INCLUDES
 *********************************************************************************************************************/
#include "delay_interface.h"
#include "delay_cfg.h"
/**********************************************************************************************************************
 *  GLOBAL DATA
 *********************************************************************************************************************/
 
 
 /**********************************************************************************************************************
 *  GLOBAL FUNCTION IMPLEMENTATION
 *********************************************************************************************************************/
 en_DELAY_error_t DELAY_init (void)
 {
	 en_DELAY_error_t returnValue = DELAY_OK;
	 
	 
	 if ( TIMER_init() )
	 {
		 returnValue = DELAY_NOK;
	 }
	 else
	 {
		 /*returnValue = DELAY_OK*/
	 }
	 if ( TIMER_disableInterrupt(DELAY_TIMER_USED) )
	 {
		 returnValue = DELAY_NOK;
	 }
	 else
	 {
		 /*returnValue = DELAY_OK*/
	 }
	 if ( TIMER_stop(DELAY_TIMER_USED) )
	 {
		 returnValue = DELAY_NOK;
	 }
	 else
	 {
		 /*returnValue = DELAY_OK*/
	 }
	 return returnValue;
 }

 en_DELAY_error_t DELAY_setTime (f32 f32_a_timeInMS)
 {
	 en_DELAY_error_t returnValue = DELAY_OK;
	 
	 if ( TIMER_stop(DELAY_TIMER_USED) )
	 {
		 returnValue = DELAY_NOK;
	 }
	 else
	 {
		 /*returnValue = DELAY_OK*/
	 }
	 
	 if ( TIMER_setDelayTime(DELAY_TIMER_USED, f32_a_timeInMS) )
	 {
		 returnValue = DELAY_NOK;
	 }
	 else
	 {
		 /*returnValue = DELAY_OK*/
	 }
	 
	 return returnValue;
	 
 }

/**********************************************************************************************************************
 *  END OF FILE: delay_program.c
 *********************************************************************************************************************/
