/**********************************************************************************************************************
 *  FILE DESCRIPTION
 *  -----------------------------------------------------------------------------------------------------------------
 *
 *         @Date:  	11:23 PM Monday, May 15, 2023
 *		   @File:  	delay_program.c         
 *		 @Module:  	Delay generated by timer on normal mode
 *		 @Author:	Ahmed Hesham
 *  @Description:  	Program file for Delay generated by timer on normal mode
 *  
 *********************************************************************************************************************/

/**********************************************************************************************************************
 *  INCLUDES
 *********************************************************************************************************************/
#include "delay_interface.h"
#include "delay_cfg.h"
/**********************************************************************************************************************
 *  GLOBAL DATA
 *********************************************************************************************************************/

 
 /**********************************************************************************************************************
 *  GLOBAL FUNCTION IMPLEMENTATION
 *********************************************************************************************************************/
 /******************************************************************************
 * @Syntax          : en_DELAY_error_t DELAY_init (void)
 * @Description     : Initializes delay module
 * @Sync\Async      : Synchronous
 * @Reentrancy      : Reentrant
 * @Parameters (in) : None
 * @Parameters (out): None
 * @Return value:   : en_DELAY_error_t		DELAY_OK = 0
 *											DELAY_NOK = 1
 *******************************************************************************/
 en_DELAY_error_t DELAY_init (void)
 {
	 en_DELAY_error_t returnValue = DELAY_OK;
	 
	 
	 if ( TIMER_init() )
	 {
		 returnValue = DELAY_NOK;
	 }
	 else
	 {
		 /*returnValue = DELAY_OK*/
	 }
	 if ( TIMER_disableInterrupt(DELAY_TIMER_USED) )
	 {
		 returnValue = DELAY_NOK;
	 }
	 else
	 {
		 /*returnValue = DELAY_OK*/
	 }
	 if ( TIMER_pause(DELAY_TIMER_USED) )
	 {
		 returnValue = DELAY_NOK;
	 }
	 else
	 {
		 /*returnValue = DELAY_OK*/
	 }
	 return returnValue;
 }

 /******************************************************************************
 * @Syntax          : en_DELAY_error_t DELAY_setTime (f32 f32_a_timeInMS)
 * @Description     : Sets blocking delay time
 * @Sync\Async      : Synchronous
 * @Reentrancy      : Reentrant
 * @Parameters (in) : f32					f32_a_timeInMS
 * @Parameters (out): None
 * @Return value:   : en_DELAY_error_t		DELAY_OK = 0
 *											DELAY_NOK = 1
 *******************************************************************************/
en_DELAY_error_t DELAY_setTime (f32 f32_a_timeInMS)
 {
	 en_DELAY_error_t returnValue = DELAY_OK;
	 
	 if ( TIMER_disableInterrupt(DELAY_TIMER_USED) )
	 {
		 returnValue = DELAY_NOK;
	 }
	 else
	 {
		 /*returnValue = DELAY_OK*/
	 }
	 
	 if ( TIMER_pause(DELAY_TIMER_USED) )
	 {
		 returnValue = DELAY_NOK;
	 }
	 else
	 {
		 /*returnValue = DELAY_OK*/
	 }
	 
	 if ( TIMER_setDelayTime(DELAY_TIMER_USED, f32_a_timeInMS) )
	 {
		 returnValue = DELAY_NOK;
	 }
	 else
	 {
		 /*returnValue = DELAY_OK*/
	 }
	 
	 if ( TIMER_enableInterrupt(DELAY_TIMER_USED) )
	 {
		 returnValue = DELAY_NOK;
	 }
	 else
	 {
		 /*returnValue = DELAY_OK*/
	 }
	 
	 return returnValue;
	 
 }

/******************************************************************************
* @Syntax          : en_DELAY_error_t DELAY_setTime (f32 f32_a_timeInMS)
* @Description     : Sets non-blocking delay time
* @Sync\Async      : Synchronous
* @Reentrancy      : Reentrant
* @Parameters (in) : f32					f32_a_timeInMS
* @Parameters (out): None
* @Return value:   : en_DELAY_error_t		DELAY_OK = 0
*											DELAY_NOK = 1
*******************************************************************************/
en_DELAY_error_t DELAY_setTimeNonBlocking (f32 f32_a_timeInMs)
{
	en_DELAY_error_t returnValue = DELAY_OK;
	
	if ( TIMER_disableInterrupt(DELAY_TIMER_USED) )
	{
		returnValue = DELAY_NOK;
	}
	else
	{
		/*returnValue = DELAY_OK*/
	}
	
	if ( TIMER_pause(DELAY_TIMER_USED) )
	{
		returnValue = DELAY_NOK;
	}
	else
	{
		/*returnValue = DELAY_OK*/
	}
	
	if ( TIMER_setTime(DELAY_TIMER_USED, f32_a_timeInMs) )
	{
		returnValue = DELAY_NOK;
	}
	else
	{
		/*returnValue = DELAY_OK*/
	}
	
	if ( TIMER_enableInterrupt(DELAY_TIMER_USED) )
	{
		returnValue = DELAY_NOK;
	}
	else
	{
		/*returnValue = DELAY_OK*/
	}
	
	if ( TIMER_resume(DELAY_TIMER_USED) )
	{
		returnValue = DELAY_NOK;
	}
	else
	{
		/*returnValue = DELAY_OK*/
	}
	
	return returnValue;
}

/******************************************************************************
* @Syntax          : en_DELAY_error_t DELAY_setCallBack (void (*funPtr)(void))
* @Description     : Sets call back for the function which gonna be performed
*					 when the nonblocking delay times out
* @Sync\Async      : Synchronous
* @Reentrancy      : Reentrant
* @Parameters (in) : void					(*funPtr)(void)
* @Parameters (out): None
* @Return value:   : en_DELAY_error_t		DELAY_OK = 0
*											DELAY_NOK = 1
*******************************************************************************/
en_DELAY_error_t DELAY_setCallBack (void (*funPtr)(void))
{
	en_DELAY_error_t returnValue = DELAY_OK;
	
	
	if ( TIMER_setCallBack(DELAY_TIMER_USED, funPtr) )
	{
		returnValue = DELAY_NOK;
	}
	else
	{
		/*returnValue = DELAY_OK*/
	}
	
	return returnValue;
}
/**********************************************************************************************************************
 *  END OF FILE: delay_program.c
 *********************************************************************************************************************/
